### ISSUE TITLE
Upgrade broke get_wordchars_utf16

### ISSUE THREAD

**Issue by jeroenooms** [hunspell/hunspell#387] opened 2016-05-19 11:03 UTC
My libhunspell bindings have a line like this as documented in `man 3 hunspell`

``` c
unsigned short * utf16_wc;
int utf16_len;
utf16_wc = mydict->get_wordchars_utf16(&utf16_len);
```

After debian ugpraded hunspell to 1.4. this is now broken. Is it intended/expected that this upgrade breaks the API? If so you should probably update `man` and introduce some kind of `HUNSPELL_VERSION` macro so the driver can build against both 1.3 and 1.4. But it probably would have been nicer to add a separate function for the new API and leave the old one working...

```
g++ -I/home/hornik/tmp/R.check/r-patched-gcc/Work/build/include -DNDEBUG -I/usr/include/hunspell -I/usr/local/include -I"/home/hornik/tmp/R.check/r-patched-gcc/Work/build/Packages/Rcpp/include"   -fpic  -g -O2 -Wall -Wno-unused -pedantic -mtune=native -c RcppExports.cpp -o RcppExports.o
g++ -I/home/hornik/tmp/R.check/r-patched-gcc/Work/build/include -DNDEBUG -I/usr/include/hunspell -I/usr/local/include -I"/home/hornik/tmp/R.check/r-patched-gcc/Work/build/Packages/Rcpp/include"   -fpic  -g -O2 -Wall -Wno-unused -pedantic -mtune=native -c check.cpp -o check.o
In file included from check.cpp:1:0:
utils.h: In member function ‘short unsigned int* hunspell_dict::get_wordchars_utf16(int*)’:
utils.h:52:41: error: no matching function for call to ‘Hunspell::get_wordchars_utf16(int*&)’
     return pMS_->get_wordchars_utf16(len);
                                         ^
In file included from utils.h:1:0,
                 from check.cpp:1:
/usr/include/hunspell/hunspell.hxx:220:30: note: candidate: const std::vector<w_char>& Hunspell::get_wordchars_utf16()
   const std::vector<w_char>& get_wordchars_utf16();
                              ^
/usr/include/hunspell/hunspell.hxx:220:30: note:   candidate expects 0 arguments, 1 provided
```

**Comment by reneengelhard** [comment] 2016-05-20 10:42
AFAICS that was done in                                                         

```                                                                                
commit 6f9e403ab758c9db9ddcebe86f237e336f4a5624                                 
Author: Caolán McNamara <caolanm@redhat.com>                                    
Date:   Thu Apr 14 17:26:28 2016 +0100                                          
                                                                                
    convert ignorechars_utf16 to vector                                         
```
                                                                                
which did                                                                       

```                                                                                
@@ -3680,9 +3675,8 @@ const char* AffixMgr::get_wordchars() const {             
   return wordchars;                                                            
 }                                                                              
                                                                                
-const w_char* AffixMgr::get_wordchars_utf16(int* len) const {                  
-  *len = wordchars_utf16.size();                                               
-  return &wordchars_utf16[0];                                                  
+const std::vector<w_char>& AffixMgr::get_wordchars_utf16() const {             
+  return wordchars_utf16;                                                      
 }                                                                              
                                                                                
 // is there compounding?                                                       
```
                                                                                
and                                                                             

```                                                                                
-  const w_char* get_wordchars_utf16(int* len) const;                           
+  const std::vector<w_char>& get_wordchars_utf16() const;                      
```
                                                                                
so it probably was intended.  

(And as said in my reply in the Debian Bug (fwiw, http://bugs.debian.org/824840), the SONAME didn't change for no reason.)

**Comment by dimztimz** [comment] 2016-05-29 22:50
The API and the whole library got modernized with C++ style code. It had a lot of C style code previously. You can try and recreate the old function using the new function and then send a pull request. The old style function should be marked as depracated. See hunspell.hxx for example.

**Comment by jeroenooms** [comment] 2016-05-30 14:05
Yeah I noticed there were other API changes in `hunspell.hxx` as well. This broke much of our software that was assuming the old API. It probably would have been appropriate to bump the major version, or, introduce new names for the new API and keep the old ones as legacy wrappers.

**Comment by dimztimz** [comment] 2016-07-17 16:14
I was thinknig about and maybe this strategy should be used:
in 1.5 return full API compatibility with 1.3. New names may be introduced for new API
One already is (a single letter T is different):

```cpp
const std::string& get_dict_encoding() const;
H_DEPRECATED const char* get_dic_encoding() const;
```

In 2.0 we may safely remove the old API and the old and new names will become equivalent.

There are 4 functions in the new API that are incompatible with the old. 3 of them are more problematic as we can not do the function overload trick.

New API functions:

```cpp
const std::string& get_wordchars() const;
const std::vector<w_char>& get_wordchars_utf16() const;
const std::string& get_version() const;
bool input_conv(const std::string& word, std::string& dest);
```

Old API functions:

```cpp
const char* get_wordchars();
unsigned short* get_wordchars_utf16(int* len);
const char* get_version();
int input_conv(const char* word, char* dest, size_t destsize)
```

The first three can get new names, and naming is kinda sensitive topic, almost as sensitive as tabs vs spaces. I was thinking of something like 

```cpp
const std::string& get_wordchars_newapi() const; //or
const std::string& get_wordchars_cppapi() const;
```

And last but not least, creating a completely new class for the new API also makes sense.

I think others should comment on this. What were the previous experiences with this situation?

**Comment by jeroenooms** [comment] 2016-07-17 16:34
Yes that would be much better than breaking old API's. Perhaps you can put new API's in a C++ namespace? `hunspell::get_wordchars()` etc?

**Comment by dimztimz** [comment] 2016-09-16 11:18
I was just looking into this, and fixing isn't as straightforward.

Internally the type `w_char` is used everywhere for UTF-16 code units in 1.4 version and up, so I can't just simply return an array of shorts for `get_wordchars_utf16()`. `w_char` (not `wchar_t`) is defined as struct of two `char` variables.

 I would have to:

1. add an additional vector of shorts as a class variable in AffixMgr (not as a local variable)
2. convert the vector of w_char to vector of shorts
3. return the .data() of the new vector.

Thinking about this I got to the idea that using w_char is just a bad idea for UTF-16, and exposing the type in a public API is even worse. Doing the above solution is just a quick and dirty solution.

**Closed** 2016-11-26 17:55 UTC
Labels: wontfix
