### ISSUE TITLE
Configurable path to dictionary

### ISSUE THREAD

**Issue by pedz** [hunspell/hunspell#420] opened 2016-10-31 21:24 UTC
I built hunspell with --prefix set to an unusual value due to my environment.  I happen to be building it for AIX but I'm not sure that is important.  The list of directories searched for a dictionary is "fixed".  I know you can specify it via environment or command line option but I don't want to teach my users how to do that each time.

Some of the paths are /usr/share/... I would suggest adding paths based upon the prefix with /shared/hunspell appended.  e.g. if prefix is set to /usr/local, then /usr/local/share/hunspell would be in the search path.

It also seems like adding all the open office paths should be a configuration option.

Also, it was not real trivial to figure out where to put the dictionary.  First I had to figure out to use -D to get the list of directories along with various reading of the man pages.  It may help to add something about the topic in the INSTALL file.

**Comment by dimztimz** [comment] 2016-10-31 23:12
Seems like duplicate of #273 and #413.

**Comment by dimztimz** [comment] 2017-01-09 04:57
How about searching the dictionaries in both `/usr/share/hunspell` and in `/usr/local/share/hunspell` ? Additionaly in `~/.local/share/...`

**Comment by dimztimz** [comment] 2017-01-10 14:13
The logic I put for searching dictionaries for v2 should be good. Moreover we have too many issues about searching dicts. So closing this.

**Closed by dimztimz** 2017-01-10 14:13 UTC
