### ISSUE TITLE
`const char *get_wordchars()` is missing for v1.4 compatibility

### ISSUE THREAD

**Issue by jbeich** [hunspell/hunspell#431] opened 2016-11-26 09:33 UTC
ChangeLog for 1.5 says `API is same as 1.4` but Sigil-Ebook/Sigil#261 proves otherwise.

**Comment by dimztimz** [comment] 2016-11-26 16:18
The API changed from 1.3 to 1.4. Seems like that function also changed in 1.4 to 1.5.

I really don't plan fixing this unless someone else provides a patch. I'm focused on version 2. Patches for v1.5 should be done in the branch ver1-5.

**Comment by dimztimz** [comment] 2016-11-26 16:30
Aha I see. There was a change in API using modern C++ types and I actually though that 1.4 had those changes, but it only had little of them, the more important methods like spell() and suggest() are same as the old API. 1.4 was released before I got into the team.

1.5 has even more changes and the public API uses the C++ types in all functions.

There is no going back. Version 2.0 will again have changes in API although I will try be as painless as possible.

**Comment by dimztimz** [comment] 2016-11-26 16:39
I will remove the notice `API is same as 1.4` in v1.5.1.

**Comment by dimztimz** [comment] 2016-11-26 17:15
Also, duplicate of #387 .

**Comment by dimztimz** [comment] 2016-11-26 17:30
Ok, i re-released v.1.5.0 with a fixed change log notice. Hopefully that should clarify things :).

**Comment by dougmassay** [comment] 2016-11-26 23:17
> Hopefully that should clarify things :).

It certainly does. It means that other projects (which use hunspell) that need to be able to be built on systems regardless of whether their repos supply hunspell v1,4 or hunspell v1,5 are in a bit of a bind now. 

Interface-breaking changes should have been held off until version 2.0. This is quite disappointing.

**Comment by dimztimz** [comment] 2016-11-27 01:20
Ok then what do you suggest.

I can either release 1.5.1 and make it compatible with 1.4 at api level. Sholud be easy, just add `return .c_str ()`  Here and there. Maybe you can make a patch.

**Comment by dimztimz** [comment] 2016-11-27 01:21
I can also pull 1.5 and release it as v2.

**Comment by dimztimz** [comment] 2016-11-27 11:42
Ok I removed version 1.5.0 from the page Releases so far. I will fix things about the API when I can and release version 1.5.1. Two api problem were reported in the same day #432.

For now, I will take a break.

**Comment by dimztimz** [comment] 2016-11-27 13:09
Can you test with the latest version in the branch ver1-5.

**Comment by dougmassay** [comment] 2016-11-27 14:34
I see no problems (with regard to Sigil and get_wordchars()) using the ver1-5 branch. No compilation errors, functionality appears to be restored.

Thanks for looking into this.

**Closed** 2016-11-27 17:17 UTC
Labels: bug

**Comment by dimztimz** [comment] 2016-11-27 18:07
I released v1.5.1. Can you please test with that.

**Comment by jbeich** [comment] 2016-11-27 19:39
Sigil 0.9.7 builds fine here as well against Hunspell 1.5.1. Build log: http://sprunge.us/XVGf
Other consumers are tested via [FreeBSD bug 214837](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=214837).

**Comment by dimztimz** [comment] 2016-11-27 21:57
I see there was a bug with const at get_dic_encoding()
I fixed that too https://github.com/hunspell/hunspell/releases/tag/v1.5.2

I think this is the last of them. If there is something open another issue, but please wait. I need to take few days break away from this. The 1.x code is maintenance hell.

**Comment by jbeich** [comment] 2016-11-28 11:42
> I see there was a bug with const at get_dic_encoding()

A minor API incompatibility that helps to uncover some ABI nastiness like in [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1320621) or Texmaker which can cause crashes. I've added back `const` in FreeBSD port.

**Comment by dimztimz** [comment] 2016-11-28 16:35
I guess we are done with this api stuff. :)

**Comment by dougmassay** [comment] 2016-11-28 16:37
Thanks for taking the time to address it. It's very-much appreciated!
