### ISSUE TITLE
Emoji in text causes segfault

### ISSUE THREAD

**Issue by jeroen** [hunspell/hunspell#493] opened 2017-05-08 08:27 UTC
A user has reported a problem in the R bindings that's probably a bug in libhunspell: https://github.com/ropensci/hunspell/issues/25

**Comment by caolanm** [comment] 2022-08-21 20:54
This looks like a duplicate of https://github.com/hunspell/hunspell/issues/583

**Closed by caolanm** 2022-08-21 20:54 UTC
