### ISSUE TITLE
Bug in Hunspell (tested only in Thunderbird)

### ISSUE THREAD

**Issue by marcoagpinto** [hunspell/hunspell#391] opened 2016-06-27 20:28 UTC
Log of private conversation reporting the bug:

[21:22] <marcoagpinto> and there is a bug in Hunspell
[21:22] <marcoagpinto> I found it the other day
[21:23] <marcoagpinto> Neo-Gothic
[21:23] <marcoagpinto> this word always appear as a typo because the correct word is "neo-Gothic"
[21:23] <marcoagpinto> "neo" in lowercase
[21:24] <marcoagpinto> but it suggests in uppercase
[21:24] <marcoagpinto> :)
[21:24] <marcoagpinto> at least in Thunderbird where I tried it
[21:24] <marcoagpinto> I thought about sending an e-mail to László...
[21:24] <marcoagpinto> but he never replies anyway
[21:25] <marcoagpinto> :(

**Comment by marcoagpinto** [comment] 2016-06-27 20:33
en_GB (forked by me)

**Comment by dimztimz** [comment] 2016-07-01 02:34
What are the dictionary entries for neo and gothic? Does one of them start with uppercase?

**Comment by marcoagpinto** [comment] 2016-07-04 11:25
@dimztimz 
The correct word is "neo-Gothic".

It is in my forked version of the British speller.

**Comment by dimztimz** [comment] 2016-07-04 13:38
I see now.

The .dic entry is ```neo-Gothic```.
If I write neo-Gothic, it's OK. If O write Neo-Gothic, the word get's underlined bit the suggestion is the same.

The bug happens with any word that has a capital letter somewhere in the middle.
And it probably happens in the spell() method, while the suggest() method thinks the word is OK and just suggests the same word.

**Comment by dimztimz** [comment] 2016-09-16 12:57
Duplicate of #106, closing here.

**Closed by dimztimz** 2016-09-16 12:57 UTC
Labels: bug, duplicate
