### ISSUE TITLE
Realloc leak in hunspell.cxx:1504

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#239] opened 2015-05-27 06:59 UTC
Visual Studio code analysis picked this up, [a C6308](https://msdn.microsoft.com/en-us/library/kkedhy7c.aspx).

In function `add`, at the line:

    dest = (char *) realloc(dest, strlen(dest) + strlen(st) + 1);

...if `realloc` fails, `dest` is assigned NULL, and the address of the original allocation is clobbered, thus leaking the memory.

    C6308	Realloc leak
    1504	'realloc' might return null pointer: assigning null pointer to 'dest', which is passed as an argument to 'realloc', will cause the original memory block to be leaked.

Original comment by: ariccio

Original Ticket: [hunspell/bugs/272](https://sourceforge.net/p/hunspell/bugs/272)

**Comment by ariccio** [comment] 2015-08-11 23:27
Self-xref: @ariccio

**Comment by dimztimz** [comment] 2016-09-16 12:25
Duplicate of #152 . This is fixed in 866e0ea935579a4211aa329852e39fdcdcc2c908.

**Closed by dimztimz** 2016-09-16 12:25 UTC
Labels: auto-migrated, leak, sourceforge, v1.0 (example)
