### ISSUE TITLE
hungarian string causes crash in hyphenate

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#235] opened 2015-04-27 12:19 UTC
Hi,

I using the current hunspell86.dll Version 1.2.554.16953 from nuget with NHunspell .Net wrapper. 
Internal we are calling the function:
MarshalHunspellDll.HyphenHyphenate(this.unmanagedHandle, word);

Now we have a string in hungarian that cases a Crash / Segmentation fault.

Examples:

"Vakuumszivattyz: szama szivattyz"

or 

"Vakuumszivattyz: tzllipte a bekapcsolasok srankinti maximalis szamat. A bekapcsolasok szamanak tzllipise a szivattyz karosodasat okozza."

Please fix this bug.

Thanks,

Gregor

Original comment by: glgweeke

Original Ticket: [hunspell/bugs/268](https://sourceforge.net/p/hunspell/bugs/268)

**Comment by dimztimz** [comment] 2016-09-15 17:06
Duplicate of #12 and hunspell/hyphen#11. Closing here.

**Closed by dimztimz** 2016-09-15 17:06 UTC
Labels: auto-migrated, duplicate, sourceforge, v1.0 (example)
