### ISSUE TITLE
[Question] I can not create English-Russian Dictionary

### ISSUE THREAD

**Issue by Kristinita** [hunspell/hunspell#425] opened 2016-11-14 15:33 UTC
### Briefly

I can not merge English and Russian dictionaries.

### Detail

I use Sublime Text editor [uses Hunspell for its spell checking](http://www.sublimetext.com/docs/3/spell_checking.html). In [this comment](https://github.com/SublimeTextIssues/Core/issues/1069#issuecomment-257945467) I read, what I can make bilingual spell check. But I can not do it.

### My dictionaries

English and Russian dictionaries:

+ [EN.aff](https://github.com/titoBouzout/Dictionaries/blob/master/English%20(American).aff)
+ [EN.dic](https://github.com/titoBouzout/Dictionaries/blob/master/English%20(American).dic)
+ [EN.txt](https://github.com/titoBouzout/Dictionaries/blob/master/English%20(American).txt)
+ [RU.aff](https://github.com/titoBouzout/Dictionaries/blob/master/Russian.aff)
+ [RU.dic](https://github.com/titoBouzout/Dictionaries/blob/master/Russian.dic)
+ [RU.txt](https://github.com/titoBouzout/Dictionaries/blob/master/Russian.txt)

Manually merge dictionaries:

+ [EN_RU.dic](https://gist.github.com/f03b9bb901d61be4a19feb13e12f62b9)
+ [EN_RU.aff](http://pastebin.com/1g2529m2)
+ [EN-RU.txt](http://pastebin.com/XrjBkcaB)

### Expected behavior

In Russian dictionary few сorrect Russian words underline for me:

![Expected behavior](http://i.imgur.com/zp3TSZt.png)

### Actual behavior

In my manually English-Russian dictionary many сorrect Russian words underline for me:

![Actual behavior](http://i.imgur.com/KCH3hVF.png)

### Did not help

1. I find [old answer](https://sourceforge.net/p/hunspell/feature-requests/21/#f136) → I run in my terminal command `hunspell -d EN,RU` in directory of dictionaries files → but in terminal nothing occurs: was just stuck there, doing nothing, no error message.

![Command prompt](http://i.imgur.com/Ww2uH4Z.png)

2. I try run [hunspell-merge](https://github.com/arty-name/hunspell-merge/), but this program not worked for me, see [issue](https://github.com/arty-name/hunspell-merge/issues/6).

Thanks.

**Comment by dimztimz** [comment] 2016-11-14 19:35
Bilingual spellchecker is not supported, at least not in reliable way. Merging dictionaries should be out of question. 

Instead, at API level you can instantiate multiple objects of the spellchecker with different languages. Then you can check the word in each object. This is the most reliable way for now.

Multilingual spellchecker might be added out of the box in version 2.

**Comment by evandrocoan** [comment] 2016-11-15 15:44
I downloaded your `EN_RU.dic` file, it seems ok. The present problem is on the `EN_RU.aff`.

After the words on the `EN_RU.dic` file there are some special attributes presented as /12 for Russian and /WEF for English. These are the rules for the special words transformations.
Example, the word `sublime` is also correct as ``Sublime`, one of because these extra rules `sublime/YTGDRS` on it at the `EN_RU.dic` file. 
These rules `YTGDRS` are located on the `EN_RU.aff` file. But if when you merge them you, they got lost when the `hunspell` do the parse reading the `EN_RU.aff`, the `sublime` word will not be accepted as `Sublime`, then it will be marked wrong.
The same applies to the Russian words as `общелкивать/2433`.

But I do not know how to correctly put them together, (if it is possible for 2 distinct langues). You may try to learn how to write the `EN_RU.aff` file reading how to write `.aff` files.

Here I listed some:

1. http://manpages.ubuntu.com/manpages/trusty/en/man4/hunspell.4.html
1. http://stackoverflow.com/questions/7561648/how-to-make-custom-dictionary-for-hunspell
1. https://www.openoffice.org/lingucomponent/affix.readme
1. https://www.google.com/search?q=hunspell+affix+file+format

**Comment by dimztimz** [comment] 2016-11-15 18:42
Merging dictionaries is possible to some extent, but tedious. Writing automatic tool can be faster.

One has to make sure that word classes are in the same format and that there are no overlapping between the word classes in the two files. I'll mark this as duplicate of #348 and i will close it later.

**Closed** 2016-11-17 13:13 UTC
Labels: duplicate
